### ISSUE TITLE
Edit timer fails in Responsive Mode EPG pop-up

### ISSUE THREAD

**Issue by original-birdman** [E2OpenPlugins/e2openplugin-OpenWebif#1130]
If you are looking at the EPG (multi-channel list, each day in a vertical volume) and click on an entry with a timer set then try to Edit it (to, e.g.,  change the location) and save that, the change will fail.

The reason is that it sends back an `/api/timeradd` request rather than a `/api/timerchange` one, so the enigma2 code thinks you are trying to add a duplicate timer.

<  3480.5026> 18:10:57.6868 [RecordTimer] ignore double timer...

This is the (parameter-split) URI sent for my test case (which fails, as a timer already exists, but all I was trying to do was change the location):
```
http://et8000.lacknet/api/timeradd?
sRef=1%3A0%3A19%3A4440%3A4083%3A233A%3AEEEE0000%3A0%3A0%3A0%3A
end=1605211500
name=The+Booker+Prize+2020
description=Novelist+and+activist+Kit+de+Waal+follows+the+most+prestig$
disabled=0
afterevent=3
allow_duplicate=1
autoadjust=0
tags=
repeated=0
always_zap=0
justplay=0
dirname=%2Fmedia%2Fhdd%2Fmovie%2FSport%2F
vpsplugin_enabled=0
vpsplugin_overwrite=0
begin=1605209220
```

**Comment by wedebe** [comment]
Hi @original-birdman , what's the build date of your image?

**Comment by original-birdman** [comment]
> Hi @original-birdman , what's the build date of your image?

About 2 days ago.

It shows up in the package list as:
```
enigma2-plugin-extensions-openwebif - 1.3.9+git3650+302dbf7-r0
```
and I was using the latest git code when searching for what was going on.

**Comment by wedebe** [comment]
@original-birdman , this should be fixed in the next build

**Comment by original-birdman** [comment]
> @original-birdman , this should be fixed in the next build

I now have `1.3.9+git3670+f9813ef-r0` which _appears_ to include the fixes mentioned, but the code is still sending a `timeradd` request rather than a `timerchange` one, and so it is failing.

**Comment by original-birdman** [comment]
Now on to `1.3.9+git3732+a8eac35-r0`.
The problem still persists, and I can see _nothing_ in the code of the referenced change that would have had any affect on it.
So mystified as to what to do.

**Comment by wedebe** [comment]
If you've got a pre-July image it might be worth trying one of those as that's well before I started contributing to owif. It's a long shot, purely as a baseline reference.

I intend to rework timers in the future.

**Comment by original-birdman** [comment]
This has actually been an issue for quite some time. It's only my report that is new.
