### ISSUE TITLE
Multi EPG redraw issue

### ISSUE THREAD

**Issue by JanGruuthuse** [E2OpenPlugins/e2openplugin-OpenWebif#253]
*Open in new window* does open, content does not match up with *epgsearch* results?
If have BBC 2 and 4 HD (sat) and search for **Great British Railway Journeys**
Then select [Open in new window] the results are not past on to new window
*epgsearch*: "BBC Two Eng Tue 10.02.2015 	Great British Railway Journeys 11:05 - 11:35 (30 min.)
..."
*new open window*: "horror channel Tue 10.02.2015 	New Adventures Of Wonder Woman
..."
the original search results not showing up/missing completly in *new open window*

**Comment by jbleyel** [comment]
Is this issue only on epg search or on channel epg too?

**Comment by JanGruuthuse** [comment]
Channel epg?
The one you get on Main -> Televison -> showing now and next / channel?
Or TV Multi EPG?
Seem to have issues with redraw of the Multi Epg content using horizontal sliders.
Need more testing on this: started a new EPGrefresh to check if data is there and will test this again if data is missing there?

**Comment by jbleyel** [comment]
epgsearch is fixed

Could you please provide a screenshot with the redraw issue of multi epg?

**Comment by JanGruuthuse** [comment]
setup here 16:9 monitor and 9:16 monitor 90° turned: see desktop
![desktop](https://cloud.githubusercontent.com/assets/5527586/6135366/50cad7c6-b168-11e4-9902-8fdf0acd3cee.png)
16:9 shows arte and the rest
![169](https://cloud.githubusercontent.com/assets/5527586/6135380/76cd5dae-b168-11e4-8e10-a8353dbb57e1.png)
9:16 shows arte partial and stops
![90 monitor](https://cloud.githubusercontent.com/assets/5527586/6135384/8093dfb6-b168-11e4-90a7-1e74b07c428e.png)

**Comment by JanGruuthuse** [comment]
Seems the epgsearch issue is still there after OpenPLi update:
System OE: 	PLi-OE
Distro: 	openpli
Firmware version: 	4.0
Driver date: 	3.12.1+20140103-r1.3
Kernel version: 	3.12.1
Gui version: 	2015-02-10

enigma2-plugin-extensions-openwebif - 1+git40+43b57ee8c0-r0.0
Is there a way to attache a zip or 7z file?
original search window

![epgsearch](https://cloud.githubusercontent.com/assets/5527586/6142979/fcdcb234-b1c0-11e4-92ea-cbe6792e00d2.png)

Previously you would see see the search string in the address bar. Data does not match.
![not matching](https://cloud.githubusercontent.com/assets/5527586/6142984/135e69c6-b1c1-11e4-93ef-b5d6e037f238.png)

**Comment by jbleyel** [comment]
the epgsearch issue is fixed here.
you need to wait of the update for your distro

**Comment by JanGruuthuse** [comment]
There was a small glitch with the distro update, that is solved in OpenPLi now.
Confirmed: both issues are gone. Big thank you, again.

**Comment by ims21** [comment]
MultiEPG - popup window on event is not opened more (cca 2 days). Temporary status due progress ?

**Comment by ims21** [comment]
File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 66, in loadTemplate
    return str(mod(searchList=args))
  File "/usr/lib/python2.7/site-packages/Cheetah/Template.py", line 1005, in __str__
    rc = getattr(self, mainMethName)()
  File "/home/martin/oe4_formuler1/build/tmp/work/formuler1-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+c2f476ccaf-r0/git/plugin/controllers/views/ajax/event.py", line 187, in respond

NameMapper.NotFound: cannot find 'ref' while searching for 'channel.ref'

**Comment by jbleyel** [comment]
you need to update all files.

**Comment by jbleyel** [comment]
You need to update event.tmpl, ajax.py and services.py.

**Comment by ims21** [comment]
update software or --force-reinstall does not help ?

**Comment by jbleyel** [comment]
please wait for the next commit
